---
title: "Reproducing a network_metaanalysis from Meco 2026 (DOI: 10.1016/j.jcrc.2025.155330)"
number-sections: true #Нумерация глав
---

# Часть 1

```{r}
#| label: load-libraries-and-data
#| warning: false

if (!require("pacman")) install.packages("pacman")
library(pacman)

pacman::p_load('BUGSnet', 'dplyr', 'tidyr', 'stringr', 'ggplot2', 'cowplot', 'googlesheets4')
set.seed(12345)

gs4_deauth()
data_raw <- read_sheet('14aXdaoIlexEhEPIVylDPF3HLr28ChyRIYGMEqWnDI0A',
           sheet = 'Sheet2',col_types = "c",skip = 1) |> 
  mutate(across(contains('n_'), as.numeric)) |> 
  filter(analyzed_population == 'Per-Protocol' | (study == 'Dellinger 2018' & analyzed_population == '> 9 MODS primary analyses'))

```

```{r}
#| label: events-data
#| warning: false

data_raw |> select(study,group_code, contains('events')) |> 
  group_by(study) |> 
  slice(1) |>  ungroup() |> 
  summarise(across(starts_with("n_events"), ~ sum(!is.na(.))))  |> 
  pivot_longer(
    cols = everything(),
    names_to = "endpoint",
    values_to = "n_studies"
  )

```


```{r}
#| label: study-data
#| warning: false

data_raw |> 
  group_by(study) |> 
  summarise(
    across(starts_with("n_events"), ~ any(!is.na(.)))
  ) |> 
  rowwise() |> 
  mutate(n_endpoints = sum(c_across(starts_with("n_events")))) |> 
  ungroup() |>  select(study, n_endpoints)

```

```{r}
#| label: time-choice
#| warning: false

event_cols <- grep('n_events', colnames(data_raw), value = T)

study_endpoints <- data_raw |> 
  group_by(study) |> 
  summarise(
    across(event_cols, ~ first(.)),
    .groups = "drop"
  ) |>  
     rowwise() |> 
  mutate(
    nearest_28_name = if (!is.na(`n_events_28-30`)) {
      "28-30"
    } else {
      # which.min возвращает индекс минимального значения в векторе 
      col_index <- which.min(c_across(all_of(event_cols)))
      sub("n_events_", "", event_cols[col_index])
    },
    
    nearest_hospt_name = if (!is.na(n_events_hospt)) {
      "hospt"
    } else {
      col_index <- which.max(c_across(all_of(event_cols)))
      sub("n_events_", "", event_cols[col_index])
    },
  ) |> 
  ungroup() |> select(study, contains('nearest'))

data_with_endpoints <- left_join(data_raw,study_endpoints, by = 'study')



date_28 <- data_with_endpoints |> 
  rowwise() |> 
  mutate(
    nearest_28_events = get(paste0("n_events_", nearest_28_name)),
    nearest_28_at_risk = get(paste0("n_at_risk_", nearest_28_name))
  ) |> 
  ungroup() |> 
  select(study, group_code, n_events = nearest_28_events, n_patients = nearest_28_at_risk)


max_date <- data_with_endpoints |> 
  rowwise() |> 
  mutate(
    nearest_hospt_events = get(paste0("n_events_", nearest_hospt_name)),
    nearest_hospt_at_risk = get(paste0("n_at_risk_", nearest_hospt_name))
  ) |> 
  ungroup() |> 
  select(study, group_code, n_events = nearest_hospt_events, n_patients = nearest_hospt_at_risk)


```




```{r}
#| label: table-preparation
#| warning: false


prep_template <- \(df){

  date_28 |>
    select(study, starts_with(c("group_code", "n_events", "n_patients"))) |>
    rename(
      Treatment = group_code,
      r = n_events,
      n = n_patients,
      Study = study
    ) |>
    filter(Treatment != '') |>
    select(Study, Treatment, r, n)

}

data_prepared_max <- prep_template(max_date)
data_prepared_28  <- prep_template(date_28)


```

```{r}
#| label: network-plot-prep
#| warning: false


# Prepare network data object for analysis
network_template <- \(dat){
  data.prep(
    arm.data = dat,
    varname.t = "Treatment",
    varname.s = "Study"
  )
}

network_data_max <- network_template(data_prepared_max)
network_data_28  <- network_template(data_prepared_28)

```

```{r}
#| label: network-plot-view
#| warning: false


plot_network <- \(network, title){

  cat("##", title, "\n")

  net.plot(
    network,
    node.scale = 3,
    edge.scale = 1.5
  )
}

# петлями обозначены сравнения исследований с более чем 2 группами
plot_network(network_data_max, "Max follow-up")
```

```{r}
plot_network(network_data_28, "28 days")
```


```{r}
#| label: network-tables-max
#| warning: false


network_char_max <- net.tab(
  data = network_data_max,
  outcome = "r",
  N = "n",
  type.outcome = "binomial"
)

network_char_28 <- net.tab(
  data = network_data_28,
  outcome = "r",
  N = "n",
  type.outcome = "binomial"
)

print(network_char_max$network)
print(network_char_max$intervention)
print(network_char_max$comparison)
```

```{r}
#| label: network-tables-28-days
#| warning: false
print(network_char_28$network)
print(network_char_28$intervention)
print(network_char_28$comparison)
```


```{r}
#| label: nma-model-creation
#| warning: false


# Standard therapy was used as the benchmark treatment.
reference_treatment <- "ST"


model_template <- \(network, effects){

  nma.model(
    data = network,
    outcome = "r",
    N = "n",
    reference = reference_treatment,
    family = "binomial",
    link = "log",
    effects = effects,
    prior.mu = "dnorm(0, 0.0001)",
    prior.d = "dnorm(0, 0.0001)",
    prior.sigma = "dunif(0, 5)"
  )

}

nma_model_random_28 <- model_template(network_data_28, "random")
nma_model_fixed_28  <- model_template(network_data_28, "fixed")

nma_model_random_max <- model_template(network_data_max, "random")
nma_model_fixed_max  <- model_template(network_data_max, "fixed")


```

```{r}
#| label: model-run
#| warning: false

# Running model
run_template <- \(model){
  nma.run(
    model,
    n.burnin = 5000,
    n.iter = 20000,
    thin = 1
  )
}

nma_results_random_28 <- run_template(nma_model_random_28)
nma_results_fixed_28  <- run_template(nma_model_fixed_28)

nma_results_random_max <- run_template(nma_model_random_max)
nma_results_fixed_max  <- run_template(nma_model_fixed_max)

```

```{r}
#| label: forest-plot
#| warning: false

extract_template <- \(res, model_label){

  do.call(rbind, res$samples) |>
    as_tibble() |>
    mutate(iter = row_number()) |>
    select(iter, matches("^d\\[")) |>
    pivot_longer(-iter,
                 names_to = "d_index",
                 values_to = "value") |>
    mutate(
      trt = res$trt.key[
        as.integer(stringr::str_extract(d_index, "\\d+"))
      ]
    ) |>
    group_by(iter) |>
    mutate(value = value - value[trt == reference_treatment]) |>
    ungroup() |>
    filter(trt != reference_treatment) |>
    summarise(
      mean = median(value),
      lci  = quantile(value, .025),
      uci  = quantile(value, .975),
      .by = trt
    ) |>
    mutate(model = model_label)

}

forest_df_28 <- bind_rows(
  extract_template(nma_results_random_28, "Random"),
  extract_template(nma_results_fixed_28, "Fixed")
)

forest_df_max <- bind_rows(
  extract_template(nma_results_random_max, "Random"),
  extract_template(nma_results_fixed_max, "Fixed")
)

plot_template <- \(df){

  df |>
    mutate(
      trt = factor(trt, levels = unique(trt)),
      trt = forcats::fct_rev(trt)
    ) |>
    ggplot(
      aes(trt, mean, ymin = lci, ymax = uci, colour = model)
    ) +
    geom_pointrange(position = position_dodge(.5)) +
    geom_hline(yintercept = 0, linetype = 2) +
    coord_flip() + 
    labs(x =  'Treatment',
         y = 'Risk Ratio relative to ST')+
    theme_classic()

}

g1 <- plot_template(forest_df_28)
g2 <- plot_template(forest_df_max)

cowplot::plot_grid(g1, g2)

```

```{r}
#| label: leverage-plot-28
#| warning: false

par(mfrow = c(1, 2))

# Leverage plots for model diagnostics
fe_fit <- nma.fit(
  nma_results_fixed_28,
  main = "Fixed Effects Model 28 days"
)
re_fit <- nma.fit(
  nma_results_random_28,
  main = "Random Effects Model 28 days"
)
par(mfrow = c(1, 1)) 


```

```{r}
#| label: leverage-plot=max
#| warning: false
par(mfrow = c(1, 2))

# Leverage plots for model diagnostics
fe_fit <- nma.fit(
  nma_results_fixed_max,
  main = "Fixed Effects Model max days"
)
re_fit <- nma.fit(
  nma_results_random_max,
  main = "Random Effects Model max days"
)
par(mfrow = c(1, 1)) 


```



